version: '3.3'
services:
  db:
    image: mysql:5.7
    restart: always
    container_name: "etreprof-db"
    environment:
      MYSQL_DATABASE: 'Etreprof_DB'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
    volumes:
      - ~/mysql_data:/var/lib/mysql
    networks:
      - etreprof_network

  backend:
    container_name: etreprof-backend
    build:
      context: ./etreprof-backend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    volumes:
       - ./etreprof-backend:/app
    depends_on:
      - db
    networks:
      - etreprof_network

  frontend:
    container_name: etreprof-frontend
    build:
      context: ./etreprof-frontend
      dockerfile: Dockerfile
    depends_on:
      - db
      - backend
    networks:
      - etreprof_network

    # image: node:9-slim
    # working_dir: "/var/www/app"
    restart: always
    # environment:
      # - HOST=0.0.0.0
    ports:
      - "3019:3019"
    volumes:
      - ./etreprof-frontend:/app
    # command: bash -c "npm install && npm run dev"

networks:
  etreprof_network:
    driver: bridge
